## Funzzy events file
# more details see: https://github.com/cristianoliveira/funzzy
#
# list here all the events and the commands that it should execute

- name: run my test
  run: 'make test'
  change:
    - '**/*.vim'
    - '**/*.lua'

- name: run my linter
  run: 'make lint'
  change:
    - '**/*.vim'
    - '**/*.lua'

- name: build with nix
  run: 
    - nix flake check
    - nix build .#check --verbose -L
  change:
    - '**/*.sh'
    - '**/*.nix'
    - '**/*.vim'
    - '**/*.lua'

- name: git stage changed files
  run: 
    - git add {{relative_filepath}}
  change:
    - '**/*.sh'
    - '**/*.nix'
    - '**/*.md'
    - '**/*.vim'
    - '**/*.lua'
