name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt install build-essential libreadline-dev unzip
        sudo apt install lua5.3
        wget https://luarocks.org/releases/luarocks-3.8.0.tar.gz
        cd luarocks-3.8.0
        tar zxpf luarocks-3.8.0.tar.gz
        sudo apt-get install luarocks

    - name: Run setup
      run: make setup

    - name: Run test
      run: make test

    - name: Run lint
      run: make lint
